from luxai2021.game.constants import Constants

# Observation Vector Sizes
NUM_IDENTIFIERS = 3
NUM_GAME_STATES = 14
UNIT_VECTOR_SIZE = 7
NUM_RESOURCES = (5 * UNIT_VECTOR_SIZE) + (3 * 3 * UNIT_VECTOR_SIZE)
OBSERVATION_SHAPE = (NUM_IDENTIFIERS + NUM_GAME_STATES + NUM_RESOURCES,)
RESOURCE_LIST = [Constants.RESOURCE_TYPES.WOOD, Constants.RESOURCE_TYPES.COAL, Constants.RESOURCE_TYPES.URANIUM]

# Observation Constants
MAX_RESEARCH = 200.0
MAX_UNIT_COUNT = 30
NUM_STEPS_IN_DAY = 30
NUM_STEPS_IN_NIGHT = 10

# Reward Constants
CITY_REWARD_MODIFIER = 1
UNIT_REWARD_MODIFIER = 0.2
FUEL_REWARD_MODIFIER = 0.001
RESC_REWARD_MODIFIER = 0.0005
LEAD_REWARD_MODIFIER = .5
