# Observation Constants
NUM_IDENTIFIERS = 3
NUM_GAME_STATES = 12
MAX_RESEARCH = 200.0
MAX_UNIT_COUNT = 30

# Reward Constants
CITY_REWARD_MODIFIER = 0.0
UNIT_REWARD_MODIFIER = 0.0
FUEL_REWARD_MODIFIER = 0.0
LEAD_REWARD_MODIFIER = 0.0

